/*
 * report/report.js — renders a morning/nightly report page from data.
 *
 * Each morning_report_<date>.html / nightly_report_<date>.html is a tiny
 * shell (generated by build/build_site.py) whose <body> carries
 * data-kind, data-date and data-root. This script loads:
 *   data/reports/index.json                   — which dates exist
 *   data/reports/<kind>/<yyyy>/<date>.json    — the report's content
 *   data/daily/<yyyy>.json                    — metric series for charts
 * and rebuilds the page with the original layout and styles.
 */
(function () {
  "use strict";

  var body = document.body;
  var KIND = body.getAttribute("data-kind") || "morning";
  var ROOT = body.getAttribute("data-root") || "";
  var requested = body.getAttribute("data-date") || "latest";
  var TONE = { green: "#32d74b", yellow: "#ffd60a", red: "#ff453a", blue: "#0a84ff", orange: "#ff9f0a", purple: "#bf5af2" };
  var NAV = [
    ["nav-hub", "", "🏠 Hub"], ["nav-calendars", "calendars/", "📅 Calendars"],
    ["nav-strength", "strength/", "💪 Strength"], ["nav-running", "running/", "🏃 Running"],
    ["nav-sleep", "sleep/", "😴 Sleep & Recovery"], ["nav-nutrition", "nutrition/", "🥗 Nutrition"],
  ];

  function getJSON(path) {
    return fetch(ROOT + path, { cache: "no-cache" }).then(function (r) {
      if (!r.ok) throw new Error(path + " → HTTP " + r.status);
      return r.json();
    });
  }
  function h(tag, attrs, html) {
    var e = document.createElement(tag);
    for (var k in attrs || {}) e.setAttribute(k, attrs[k]);
    if (html !== undefined) e.innerHTML = html;
    return e;
  }
  function esc(s) {
    return String(s).replace(/[&<>"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]; });
  }
  function addDays(s, n) {
    var p = s.split("-"), d = new Date(Date.UTC(+p[0], +p[1] - 1, +p[2] + n));
    return d.toISOString().slice(0, 10);
  }
  function reportHref(kind, date) {
    var prefix = { interactive: "interactive_nightly_", historical: "historical_progress_report_", lifting: "lifting_recovery_report_" };
    return ROOT + (prefix[kind] || kind + "_report_") + date + ".html";
  }

  // ------------------------------------------------------------ chrome --
  function renderNav() {
    var nav = h("nav", {
      id: "site-nav",
      style: "background:#1a1a2e;padding:10px 20px;text-align:center;font-size:14px;border-bottom:1px solid #333;display:flex;flex-wrap:wrap;justify-content:center;gap:8px 16px;",
    });
    NAV.forEach(function (n) {
      var a = h("a", { id: n[0], href: ROOT + n[1], style: "color:#a0aec0;text-decoration:none;" });
      a.textContent = n[2];
      nav.appendChild(a);
    });
    body.appendChild(nav);
  }

  function renderLinks(index, date) {
    // Cross-link as the originals did: morning(D) → nightly(D-1), nightly(D) → morning(D+1);
    // plus previous/next report of the same kind.
    var other = KIND === "morning" ? "nightly" : KIND === "historical" ? "lifting" : "morning";
    var otherDate = KIND === "morning" ? addDays(date, -1) : KIND === "historical" ? date : addDays(date, 1);
    var dates = index[KIND] || [], i = dates.indexOf(date);
    var btn = "display:inline-block;padding:6px 14px;background:#1c2a3a;color:#58a6ff;border:1px solid #30363d;border-radius:6px;text-decoration:none;font-size:13px;margin:8px 4px";
    var parts = [];
    if (i > 0) parts.push('<a href="' + reportHref(KIND, dates[i - 1]) + '" style="' + btn + '">← ' + dates[i - 1] + "</a>");
    if ((index[other] || []).indexOf(otherDate) >= 0) {
      var label = other === "nightly" ? "🌙 View Nightly Report (" + otherDate + ")"
        : other === "lifting" ? "💪 Lifting & Recovery (" + otherDate + ")"
        : "☀️ View Morning Report (" + otherDate + ")";
      parts.push('<a href="' + reportHref(other, otherDate) + '" style="' + btn + '">' + label + "</a>");
    }
    if (i >= 0 && i < dates.length - 1) parts.push('<a href="' + reportHref(KIND, dates[i + 1]) + '" style="' + btn + '">' + dates[i + 1] + " →</a>");
    parts.push('<a href="' + ROOT + 'report/" style="' + btn + '">📚 All reports</a>');
    body.appendChild(h("div", { class: "rc-links", style: "text-align:center;margin:8px auto" }, parts.join("")));
  }

  // ------------------------------------------------------------ content --
  function metricGrid(cards) {
    var grid = h("div", { class: "metric-grid" });
    cards.forEach(function (c) {
      var color = c.tone ? (TONE[c.tone] || c.tone) : null;
      var html = esc(c.label)
        + (c.tip ? '<span class="info-icon" data-tooltip="' + esc(c.tip) + '">i</span>' : "")
        + '<br><span class="value"' + (color ? ' style="color: ' + color + ';"' : "") + ">" + esc(c.value) + "</span>"
        + (c.sub ? " " + esc(c.sub) : "");
      grid.appendChild(h("div", { class: "card" }, html));
    });
    return grid;
  }

  function chartBox(block) {
    var box = h("div", { class: "chart-box" });
    box.appendChild(h("h2", {}, esc(block.title)));
    if (block.caption) box.insertAdjacentHTML("beforeend", block.caption);
    box.appendChild(h("div", { class: "rc-chart", "data-chart": block.chart }));
    return box;
  }

  // Run a report's own chart scripts (lifting reports use Chart.js) in order.
  function runScripts(list) {
    if (!list.length) return;
    var b = list[0], s = document.createElement("script");
    if (b.scriptSrc) {
      s.src = b.scriptSrc;
      s.onload = s.onerror = function () { runScripts(list.slice(1)); };
      body.appendChild(s);
    } else {
      s.textContent = b.script;
      body.appendChild(s);
      runScripts(list.slice(1));
    }
  }

  function renderReport(doc, series) {
    var pageScripts = [];
    document.title = doc.title;
    if (!doc.inlineTitle) body.appendChild(h("h1", {}, esc(doc.title)));
    doc.blocks.forEach(function (b) {
      if (b.metrics) body.appendChild(metricGrid(doc.metrics));
      else if (b.chart) body.appendChild(chartBox(b));
      else if (b.script || b.scriptSrc) pageScripts.push(b);
      else if (b.html) {
        var wrap = h("div", {}, b.html);
        while (wrap.firstChild) body.appendChild(wrap.firstChild);
      }
    });
    var ctx = {
      date: doc.date,
      allDays: function () {
        return Object.keys(series).sort().reduce(function (acc, y) { return acc.concat(Object.keys(series[y].days)); }, []);
      },
      day: function (d) {
        var y = series[d.slice(0, 4)], row = y && y.days[d];
        if (!row) return {};
        var o = {};
        y.fields.forEach(function (f, i) { if (row[i] !== null) o[f] = row[i]; });
        return o;
      },
    };
    // Interactive nightly: expandable cards are CSS checkbox toggles; keep keyboard support.
    Array.prototype.forEach.call(body.querySelectorAll(".card-clickable[for]"), function (label) {
      label.addEventListener("keydown", function (e) {
        if (e.key !== "Enter" && e.key !== " ") return;
        e.preventDefault();
        var box = document.getElementById(label.getAttribute("for"));
        if (box) { box.checked = !box.checked; box.setAttribute("aria-expanded", box.checked); }
      });
    });
    var slots = body.querySelectorAll(".rc-chart[data-chart], .chart-slot[data-chart]");
    Array.prototype.forEach.call(slots, function (slot) {
      try { window.ReportCharts.render(slot, slot.getAttribute("data-chart"), ctx); }
      catch (e) { slot.innerHTML = '<div class="rc-empty">Chart failed: ' + esc(e.message) + "</div>"; }
    });
    runScripts(pageScripts);
  }

  function fail(msg) {
    body.appendChild(h("div", { class: "card", style: "margin-top:24px" }, "<h2>Report unavailable</h2><p>" + esc(msg) + "</p>"));
  }

  // --------------------------------------------------------------- main --
  renderNav();
  getJSON("data/reports/index.json")
    .catch(function () { return {}; })
    .then(function (index) {
      var dates = index[KIND] || [];
      var date = requested === "latest" ? dates[dates.length - 1] : requested;
      if (!date) throw new Error("No " + KIND + " reports published yet.");
      renderLinks(index, date);
      var years = {};
      [date, addDays(date, -190)].forEach(function (d) { years[d.slice(0, 4)] = true; });
      if (KIND === "historical") {
        for (var y = 2016; y <= +date.slice(0, 4); y++) years[y] = true; // all-time charts
      }
      var yearList = Object.keys(years);
      return Promise.all([
        getJSON("data/reports/" + KIND + "/" + date.slice(0, 4) + "/" + date + ".json"),
        Promise.all(yearList.map(function (y) { return getJSON("data/daily/" + y + ".json").catch(function () { return null; }); })),
      ]).then(function (res) {
        var series = {};
        yearList.forEach(function (y, i) { if (res[1][i]) series[y] = res[1][i]; });
        renderReport(res[0], series);
      });
    })
    .catch(function (e) { fail(e.message); });
})();
